run-name: "Fast Feedback: ${{ inputs.lifecycle }}"

on:
  workflow_call:
    inputs:
      lifecycle:
        description: 'The lifecycle to run'
        type: string
        required: true
  workflow_dispatch:
    inputs:
      lifecycle:
        description: 'The lifecycle to run'
        type: string
        required: true


permissions:
  contents: write
  id-token: write

jobs:
  version:
    uses: coreeng/p2p/.github/workflows/p2p-version.yaml@v1
    with:
      version-prefix: '${{ inputs.lifecycle }}/v'
    secrets:
      git-token: ${{ secrets.GITHUB_TOKEN }}

  fastfeedback:
    needs: [version]
    uses: coreeng/p2p/.github/workflows/p2p-workflow-fastfeedback.yaml@v1
    with:
      working-directory: './${{ inputs.lifecycle }}'
      version: ${{ needs.version.outputs.version }}
