name: find-lifecycles
on:
  workflow_dispatch:
  workflow_call:
    outputs:
      lifecycles:
        description: "Lifecycles in the repository"
        value: ${{ jobs.find-lifecycles.outputs.lifecycles }}

jobs:
  find-lifecycles:
    runs-on: ubuntu-24.04
    outputs:
      lifecycles: ${{ steps.find-lifecycles.outputs.lifecycles }}
    steps:
      - uses: actions/checkout@v4
      - id: find-lifecycles
        run: |
          ./.github/scripts/find_lifecycles.sh -d . -o lifecycles.json
          lifecycles_json="$(cat lifecycles.json)"
          echo "Found lifecycles: $lifecycles_json"
          echo "lifecycles=$lifecycles_json" >> $GITHUB_OUTPUT
