name: "Fast Feedback: Matrix"

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  find-lifecycles:
    uses: ./.github/workflows/find-lifecycles.yaml
  detect-changed-lifecycles:
    needs: [find-lifecycles]
    runs-on: ubuntu-latest
    outputs:
      changed-lifecycles: ${{ steps.generate-matrix.outputs.changed_lifecycles }}
    steps:
      - uses: actions/checkout@v4
      - id: generate-scan-config
        env:
          LIFECYCLES: ${{ needs.find-lifecycles.outputs.lifecycles }}
        run: |
          files_yaml="$(echo "${LIFECYCLES[*]}" | jq 'map({(.): [(.) + "/**"]}) | add' | yq -P)"
          echo "files_yaml:"
          echo "$files_yaml"
          
          echo 'files_yaml<<EOF' >> $GITHUB_OUTPUT
          echo "$files_yaml" >> $GITHUB_OUTPUT
          echo 'EOF' >> $GITHUB_OUTPUT
      - id: changed-files
        uses: tj-actions/changed-files@v44
        with:
          files_yaml: |
            ${{ steps.generate-scan-config.outputs.files_yaml }}
      - id: generate-matrix
        env:
          changed_lifecycles: ${{ steps.changed-files.outputs.modified_keys }}
        run: |
          echo "Detected changed lifecycles: '$changed_lifecycles'"
          echo "changed_lifecycles=$(echo "${changed_lifecycles[*]}" | jq -Rc 'split(" ")')" >> $GITHUB_OUTPUT
  fast-feedback:
    needs: [detect-changed-lifecycles]
    if: needs.detect-changed-lifecycles.outputs.changed-lifecycles!= '[]'
    strategy:
      fail-fast: false
      matrix:
        lifecycle: ${{ fromJSON(needs.detect-changed-lifecycles.outputs.changed-lifecycles) }}
    uses: ./.github/workflows/fast-feedback.yaml
    with:
      lifecycle: ${{ matrix.lifecycle }}
