name: "Prod Deployment: Matrix"
on:
  workflow_dispatch:
  schedule:
    - cron: '30 5 * * 1,5'

jobs:
  find-lifecycles:
    uses: ./.github/workflows/find-lifecycles.yaml
  prod:
    needs: [find-lifecycles]
    uses: ./.github/workflows/prod.yaml
    with:
      lifecycle: ${{ matrix.lifecycle }}
    if: needs.find-lifecycles.outputs.lifecycles != '[]'
    strategy:
      fail-fast: false
      matrix:
        lifecycle: ${{ fromJSON(needs.find-lifecycles.outputs.lifecycles) }}
