run-name: "Prod Deployment: ${{ inputs.lifecycle }}"

on:
  workflow_call:
    inputs:
      lifecycle:
        description: 'The lifecycle to run'
        type: string
        required: true
  workflow_dispatch:
    inputs:
      lifecycle:
        description: 'The lifecycle to run'
        type: string
        required: true

permissions:
  contents: read
  id-token: write

jobs:
  get-image-name:
    runs-on: ubuntu-24.04
    outputs:
      image-name: ${{ steps.image-name.outputs.image_name }}
    steps:
      - uses: actions/checkout@v4
      - id: image-name
        env:
          MAKEFILE: ./${{ inputs.lifecycle }}/Makefile
        run: |
          image="$(make -f "$MAKEFILE" p2p-image)"
          echo "image_name=$image" >> $GITHUB_OUTPUT

  get-latest-version:
    needs: [get-image-name]
    uses: coreeng/p2p/.github/workflows/p2p-get-latest-image-prod.yaml@v1
    with:
      image-name: ${{ needs.get-image-name.outputs.image-name }}

  prod:
    needs: [get-latest-version]
    uses: coreeng/p2p/.github/workflows/p2p-workflow-prod.yaml@v1
    with:
      working-directory: './${{ inputs.lifecycle }}'
      version: ${{ needs.get-latest-version.outputs.version }}
      version-prefix: '${{ inputs.lifecycle }}/v'
